### ISSUE TITLE
Add OIDC support

### ISSUE THREAD

**Issue by reeseschultz** [denorians/deno_actions_core#1]
Adding OIDC support would depend on https://github.com/actions/http-client or a Deno-equivalent module.

**Comment by victoria-miltcheva** [comment]
TODO: try to import https://github.com/actions/http-client via https://esm.sh/ (https://deno.land/manual@v1.21.1/node/cdns) or a different CDN

**Comment by victoria-miltcheva** [comment]
There's no way to "polyfill" the `@actions/http-client`; it needs to be ported. I will port it and publish it on deno.land, and we can reference it as a dependency to complete OIDC support here.

**Comment by victoria-miltcheva** [comment]
See https://github.com/denorians/deno_actions_core/issues/10#issuecomment-1521083218
