### ISSUE TITLE
[BUG] Uncaught TypeError

### ISSUE THREAD

**Issue by navtoj** [denorians/deno_actions_core#10]
**Bug description:**

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/20136585/215280108-f5ebfd3f-e620-4448-baca-2807e8d323ef.png">

**Bug reproduction:**

[Link to project demonstrating the bug.](https://github.com/navtoj/debug)

1. Run the `test.ts` file code shown below.
```ts
// deno run --allow-all test.ts

import { info } from 'https://deno.land/x/deno_actions_core@0.3.0/mod.ts';

info('Hello World!');
```

**Expected behavior:**

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/20136585/215280141-ed8b727e-34b4-44dd-9694-af28a8e6cf55.png">

**Describe alternatives or workarounds you've considered:**

I've been able to successfully use the `@actions/core` npm module with [Deno's `npm:` specifier](https://deno.land/manual@v1.30.0/node/npm_specifiers).
```ts
import { info } from 'npm:@actions/core';
```

**Additional context:**

The [line shown below](https://deno.land/x/deno_actions_core@0.3.0/src/utils.ts?source=#L9) seems to be causing the issue: 
```ts
export const __dirname = dirname(fromFileUrl(import.meta.url));
```

**Comment by victoria-miltcheva** [comment]
Hi @navtoj, thank you for submitting this bug issue. Note that as of version 1.28, Deno is now supports npm packages: https://deno.com/blog/v1.28.

So now you should be able to directly use the `@actions/core` npm package that this Deno module was based off directly in your Deno project: https://github.com/actions/toolkit/tree/main#packages.

https://deno.com/manual@v1.32.5/node/npm_specifiers

I'm going to go ahead and archive this repo now that it is no longer needed.
