### ISSUE TITLE
Substitute function mocking code with a third-party module

### ISSUE THREAD

**Issue by reeseschultz** [denorians/deno_actions_core#3]
I wrote some function mocking code because I did not find an analogue for accomplishing this in Deno. I'll continue searching for a substitute. I may either contribute code to a third-party module, or make my own.

**Comment by reeseschultz** [comment]
**Update:** While working on some new stuff (that will be publicly released under @denorians soon), I found that Deno's standard library includes serious function mocking utilities now. I know this because I'm successfully using them. They can probably be used in this project to replace the old mocking code.

**Comment by victoria-miltcheva** [comment]
See https://github.com/denorians/deno_actions_core/issues/10#issuecomment-1521083218
